### ISSUE TITLE
Okay, that commit message seems to be saying they needed to remove the trailing dot from the SNI value (which is true) but they also did the same for the Host: HTTP request header without including a reason for that.  I think they just didn't consider the breakage doing that would cause.

### ISSUE THREAD

**Issue by Sujooozz** [curl/curl-cheat-sheet#3]
Okay, that commit message seems to be saying they needed to remove the trailing dot from the SNI value (which is true) but they also did the same for the Host: HTTP request header without including a reason for that.  I think they just didn't consider the breakage doing that would cause.

The SNI change is correct, the Host: header field one is not.  Can that part be reverted so curl users can execute requests with absolute domain names again?

_Originally posted by @ccazabon in https://github.com/curl/curl/issues/8290#issuecomment-1018137670_

**Comment by bagder** [comment]
This seems completely unrelated to the cheat sheet.
